# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Code Checker
run-name: Checking ${{ github.head_ref || github.ref_name }} against PMD Ruleset

on:
  push:
    branches:
      - feature/GFMC-34770
  pull_request:
      branches:
        - feature/GFMC-34770
  workflow_dispatch:

jobs:
  pmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: vwgsfcoe/pmd-github-action@main
        id: pmd
        with:
          version: '7.0.0-rc4'
          sourcePath: 'force-app/main/default/classes'
          rulesets: './pipeline/pmd/reply_ruleset.xml'
          analyzeModifiedFilesOnly: true
          displayAnnotationDescription: false
          countViolationsPriorityFilter: 2
      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1