
name: Change Wiki PMD version
run-name: Changing to PMD version ${{ github.event.inputs.pmd_version }}

on:
    workflow_dispatch:
      inputs:
        pmd_version:
          required: true
          description: What PMD version should the wiki be based on

jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'
                architecture: 'x64'
            - name: Checkout wiki code
              uses: actions/checkout@v4
              with:
                repository: ${{ github.repository }}.wiki
                token: ${{ secrets.GH_PAT }}
                path: wiki
            - name: Create environment
              run: |
                cd wiki
                python3 -m venv .env
                source .env/bin/activate
                pip3 install -r requirements.txt
            - name: Retrieve package version
              run: |
                cd wiki
                source .env/bin/activate
                python3 get_ruleset.py ${{ github.event.inputs.pmd_version }}
            - name: Update wiki
              run: |
                cd wiki
                source .env/bin/activate
                python3 generate_wiki.py
            - name: Push to wiki
              run: |
                cd wiki
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add .
                git diff-index --quiet HEAD || git commit -m "Changed version to ${{ github.event.inputs.pmd_version }}" && git push
